### ISSUE TITLE
[BUG] Error invoking callback

### ISSUE THREAD

**Issue by iclassdon** [KitsuneLab-Development/K4-DamageInfo#17]
```
16:49:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Modules.Utils.CHandle`1.get_IsValid() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Utils/CHandle.cs:line 56
   at CounterStrikeSharp.API.Modules.Entities.EntitySystem.GetEntityByHandle[T](CHandle`1 handle) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/EntitySystem.cs:line 29
   at CounterStrikeSharp.API.Modules.Utils.CHandle`1.get_Value() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Utils/CHandle.cs:line 52
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayPlayerDamageInfo(CCSPlayerController player, PlayerDamageInfo playerInfo)
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayDamageInfo(CCSPlayerController player)
   at K4ryuuDamageInfo.DamageInfoPlugin.OnPlayerDeath(EventPlayerDeath event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

```

**Comment by K4ryuu** [comment]
The problem has been solved and going to uploaded shortly.
Thank you.
