### ISSUE TITLE
[ERROR] Parameter Pointer

### ISSUE THREAD

**Issue by blady334** [KitsuneLab-Development/K4-DamageInfo#26]
Hello,

I'm reporting an error. This error appears in the console/logs from time to time, which is probably why the server crashes.

CSS Version: 195

LOGS:
2024-03-25 20:06:37.730 +01:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Core.CBaseEntity.get_Health() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBaseEntity.g.cs:line 67
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayPlayerDamageInfo(CCSPlayerController player, PlayerDamageInfo playerInfo)
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayDamageInfo(CCSPlayerController player)
   at K4ryuuDamageInfo.DamageInfoPlugin.OnPlayerDeath(EventPlayerDeath event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
2024-03-25 20:11:19.376 +01:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Core.CBaseEntity.get_Health() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBaseEntity.g.cs:line 67
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayPlayerDamageInfo(CCSPlayerController player, PlayerDamageInfo playerInfo)
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayDamageInfo(CCSPlayerController player)
   at K4ryuuDamageInfo.DamageInfoPlugin.OnPlayerDeath(EventPlayerDeath event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120

**Comment by K4ryuu** [comment]
Is your gamedata updated properly?
Which version you use?

**Comment by dizelv12** [comment]
2024-03-25 21:36:23.665 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Schema target points to null. (Parameter 'pointer')
   at CounterStrikeSharp.API.Core.CBaseEntity.get_Health() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CBaseEntity.g.cs:line 67
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayPlayerDamageInfo(CCSPlayerController player, PlayerDamageInfo playerInfo)
   at K4ryuuDamageInfo.DamageInfoPlugin.DisplayDamageInfo(CCSPlayerController player)
   at K4ryuuDamageInfo.DamageInfoPlugin.OnPlayerDeath(EventPlayerDeath event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   ---------------------------------------------------------------------------------------------------------
   i got same issue over here gamedata and everything is updated with cssharp v198
   last and now latest version of the damageinfo plugin(v2.3.0) doing this on my 50 players sv

**Comment by blady334** [comment]
Is your gamedata updated properly? - Yes
Which version you use? - The latest one, i.e. 2.3.0

**Comment by dizelv12** [comment]
i think this is about -when u hit somebody and after u hit them, if they left ur server before u die i mean plugin not yet imprinted
the damages or gethealt the other players hp it gets errors mb??

**Comment by K4ryuu** [comment]
[K4ryuuDamageInfo.dll.zip](https://github.com/K4ryuu/CS2_DamageInfo/files/14758179/K4ryuuDamageInfo.dll.zip)

Please try this version. Possibly that problem of your's is fixed and then you can come this issue.
However if it's not fixed, then don't close this issue and give a feedback here.

**Comment by blady334** [comment]
Hello,

I think it helped, but just to be sure, I'll wait another day and let you know if it solved the problem.

**Comment by K4ryuu** [comment]
I close the issue, since it seems like it got fixed. ❤️

**Comment by dizelv12** [comment]
i've been using it like 3 days in my 50 players server and it is working perfect. Thanks karyuu ur the best!
