### ISSUE TITLE
[BUG] Console errors

### ISSUE THREAD

**Issue by daffyyyy** [KitsuneLab-Development/K4-DamageInfo#6]
**Describe the bug**
On csharp v30 and server with bots dealing dmg cause error

**Logs (Optional)**
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '5' was not present in the dictionary.
   at K4ryuuDamageInfo.DamageData.UpdateDamage(CCSPlayerController attackerController, Int32 targetId, Int32 damageHP, Int32 damageArmor, Int32 Hitgroup) in /var/lib/pterodactyl/volumes/6ef877cd-d1a3-4412-8704-745b1ab7973a/game/csgo/addons/counterstrikesharp/source/CS2_DamageInfo-1.3.0/K4ryuuDamageInfo.cs:line 150
   at K4ryuuDamageInfo.DamageInfoPlugin.<Load>b__8_0(EventPlayerHurt event, GameEventInfo info) in /var/lib/pterodactyl/volumes/6ef877cd-d1a3-4412-8704-745b1ab7973a/game/csgo/addons/counterstrikesharp/source/CS2_DamageInfo-1.3.0/K4ryuuDamageInfo.cs:line 61
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '4' was not present in the dictionary.
   at K4ryuuDamageInfo.DamageData.UpdateDamage(CCSPlayerController attackerController, Int32 targetId, Int32 damageHP, Int32 damageArmor, Int32 Hitgroup) in /var/lib/pterodactyl/volumes/6ef877cd-d1a3-4412-8704-745b1ab7973a/game/csgo/addons/counterstrikesharp/source/CS2_DamageInfo-1.3.0/K4ryuuDamageInfo.cs:line 150
   at K4ryuuDamageInfo.DamageInfoPlugin.<Load>b__8_0(EventPlayerHurt event, GameEventInfo info) in /var/lib/pterodactyl/volumes/6ef877cd-d1a3-4412-8704-745b1ab7973a/game/csgo/addons/counterstrikesharp/source/CS2_DamageInfo-1.3.0/K4ryuuDamageInfo.cs:line 61
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81
```

Ty for closing prev issue, but without advertisement plugin same errors :D

**Comment by K4ryuu** [comment]
Greetings,
The latest release (v1.3.1) possibly fixed your problems.

Best Regards,
K4ryuu
